var gulp      = require( 'gulp' ),
    svgSprite = require( 'gulp-svg-sprite' ),
    rename    = require( 'gulp-rename' ),
    del       = require( 'del' );

var config = {
    mode: {
        css: {
            sprite: 'sprite.svg',
            render: {
                css: {
                    template: './gulp/templates/sprite.css'
                }
            }
        }
    }
}

/**
 *  In case of svg icon updates, i.g: deleting or adding new icons for sprite, This will remove the old one or the old svg icons and
 *  replacing it with the new one or the fresh copy.
 */
gulp.task( 'beginClean', function() {
    return del( [ './app/temp/sprite', './app/assets/images/sprite' ] );
} );


gulp.task( 'createSprite', [ 'beginClean' ], function() {
    return gulp.src( './app/assets/images/icons/**/*.svg' )
        .pipe( svgSprite( config ) )
        .pipe( gulp.dest( './app/temp/sprite' ) );
} ); // Run gulp createSprite on the command line under gulp-sprite branch to execute this code.

// Copy svg icons graphic from source 'assets/temp' folder to the main source 'app/assets'.
gulp.task( 'copySpriteGraphic', [ 'createSprite' ], function() {
    return gulp.src( './app/temp/sprite/css/**/*.svg' )
        .pipe( gulp.dest( './app/assets/images/sprites' ) );
} );

// Copying the autogenerated sprite css to the main css folder.
gulp.task( 'copySpriteCSS', [ 'createSprite' ], function() {
    return gulp.src( './app/temp/sprite/css/*.css' )
        .pipe( rename( '_sprite.css' ) )
        .pipe( gulp.dest( './app/assets/css/modules' ) );
} ); // Run gulp copySpriteCSS on the command line under gulp-sprite branch to exute this code.


// Once all of the task in 'gulp.task(icons) run, Just delete 'sprite' folder to replate it with a new and clean copy.
gulp.task( 'endClean', [ 'copySpriteGraphic', 'copySpriteCSS' ], function() {
    return del( './app/temp/sprite' );
} );


/** CREATING NEW SPRITE BY DYNAMICALLY AND NOT REPEATING 'CREATESPRITE' AND 'COPYSPRITE' CODE */
gulp.task( 'icons', [ 'beginClean', 'createSprite', 'copySpriteGraphic', 'copySpriteCSS', 'endClean' ] );
// Run gulp copySpriteCSS on the command line under gulp-sprite branch to exute this code.


/**
 *  BIG NOTES: TO PROPERLY REFLECT THE CHANGES TO THE SITE, JUST GO TO THE MAIN STYLES.CSS, JUST HIT SAVE TO TRIGGER GULP CSS BUILD. OK!
 */